CREATE TABLE transactions (
    id VARCHAR(255) PRIMARY KEY,
    customer_name VARCHAR(255) NOT NULL,
    customer_email VARCHAR(255),
    customer_phone VARCHAR(255),
    amount NUMERIC(19, 2) NOT NULL,
    payment_method VARCHAR(255),
    failure_reason VARCHAR(255),
    workflow VARCHAR(255) NOT NULL,
    status VARCHAR(255) NOT NULL,
    recurring BOOLEAN NOT NULL,
    b2b BOOLEAN NOT NULL,
    days_overdue INTEGER,
    drop_step VARCHAR(255),
    retry_count INTEGER NOT NULL,
    touches INTEGER NOT NULL,
    agent_diagnosis TEXT,
    agent_intervention VARCHAR(255),
    agent_confidence INTEGER,
    agent_message TEXT,
    agent_reasoning TEXT,
    risk_flag BOOLEAN NOT NULL,
    outcome VARCHAR(255),
    created_at TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    processed_at TIMESTAMP(6) WITHOUT TIME ZONE,
    updated_at TIMESTAMP(6) WITHOUT TIME ZONE
);
